[package]
name = "test-case-demo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ntest.workspace = true
pretty_assertions.workspace = true
test-case.workspace = true
