[package]
name = "url_demo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
env_logger.workspace = true
lazy_static.workspace = true
log.workspace = true
url.workspace = true
