[package]
name = "js_sandbox_demo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow.workspace = true
js-sandbox = "0.2.0-rc.2"
serde_json.workspace = true
